image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375

services:
  - docker:18.09.7-dind
build:
  stage: build
  image: docker:stable
  before_script:
    - apk add --no-cache docker-compose
    - docker info
  tags:
    - k8s
  script:
    - echo "Building docker images"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose build
    - docker tag blazor-template-api:latest $CI_REGISTRY_IMAGE/blazor-template-api:$CI_COMMIT_SHA
    - docker tag blazor-template-web:latest $CI_REGISTRY_IMAGE/blazor-template-web:$CI_COMMIT_SHA
    - docker tag blazor-template-api:latest $CI_REGISTRY_IMAGE/blazor-template-api:latest
    - docker tag blazor-template-web:latest $CI_REGISTRY_IMAGE/blazor-template-web:latest
    - echo "Pushing docker images to registry"
    - docker push $CI_REGISTRY_IMAGE/blazor-template-api:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/blazor-template-web:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/blazor-template-api:latest
    - docker push $CI_REGISTRY_IMAGE/blazor-template-web:latest
 
deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  tags:
    - k8s
  environment:
    name: staging
  script:
    - echo "Creating namespace, it might exists already, so force!"
    - kubectl apply -f deploy/blazor-namespace.yaml
    - echo "Adding Gitlab registry creds"
    - kubectl delete secret docker-registry registry-credentials --ignore-not-found --namespace=blazor-template
    - kubectl create secret docker-registry registry-credentials --docker-server=$CI_REGISTRY --docker-username=$CG_DEPLOY_USR --docker-password=$CG_DEPLOY_PWD --docker-email=$GITLAB_USER_EMAIL --namespace=blazor-template
    - echo "Deploy to staging environment. You must supply credentials already!"
    - kubectl apply -f deploy/blazor-deployment.yaml -f deploy/blazor-service.yaml -f deploy/blazor-ingress.yaml --namespace=blazor-template
    - echo "Creating nginx gateway"
    - kubectl apply -f deploy/nginx-configmap.yaml -f deploy/nginx-deployment.yaml -f deploy/nginx-service.yaml --namespace=blazor-template
    - echo "Rolling update"
    - kubectl rollout restart deployment -n blazor-template

