version: '3.4'

services:
  blazor-template-api:
    image: blazor-template-api
    build:
      context: .
      network: host
      dockerfile: src/BlazorTemplate/Api/Dockerfile
    restart: on-failure
    deploy:
      replicas: 1
    networks:
      - main-network
  blazor-template-web:
    image: blazor-template-web
    build:
      context: .
      network: host
      dockerfile: src/BlazorTemplate/Server/Dockerfile
    restart: on-failure
    deploy:
      replicas: 1
    networks:
      - main-network
  blazor-template-nginx:
    image: nginx:alpine
    hostname: 'blazor-template-nginx'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./nginx/logs/:/var/log/nginx/
    ports:
      - '80:80'
    depends_on:
      - blazor-template-web
      - blazor-template-api
    restart: always
    networks:
      - main-network


networks:
  main-network:
    driver: bridge
