version: '3.4'

services:
  blazor-template-api:
    image: blazor-template-api
    build:
      context: .
      network: host
      dockerfile: src/BlazorTemplate/Api/Dockerfile
    restart: on-failure
    deploy:
      replicas: 1
    networks:
      - main-network
    ports:
      - "80"
  blazor-template-web:
    image: blazor-template-web
    build:
      context: .
      network: host
      dockerfile: src/BlazorTemplate/Server/Dockerfile
    restart: on-failure
    deploy:
      replicas: 1
    networks:
      - main-network
    ports:
      - "8080:80"

networks:
  main-network:
    driver: bridge
