version: '3.4'

services:
  blazor-template-api:
    image: blazor-template-api
    build:
      context: .
      network: host
      dockerfile: src/BlazorTemplate.Api/Dockerfile
    restart: on-failure
    deploy:
      replicas: 1
    networks:
      - main-network
    ports:
      - "8080:8080"
  blazor-template-client:
    image: blazor-template-client
    build:
      context: .
      network: host
      dockerfile: src/BlazorTemplate.Client/Dockerfile
    restart: on-failure
    deploy:
      replicas: 1
    networks:
      - main-network
    ports:
      - "8081:8081"

networks:
  main-network:
    driver: bridge